package com.muscovy.game.enums;


/**
 *
 */
public enum EnemyShotType {
	SINGLE_MOVEMENT, //
	SINGLE_TOWARDS_PLAYER, DOUBLE_TOWARDS_PLAYER, TRIPLE_TOWARDS_PLAYER, //
	FOUR_DIRECTIONS, SIX_DIRECTIONS, EIGHT_DIRECTIONS, RANDOM_DIRECTION;
}
